### PR TITLE
error handling for null values

### LINKED ISSUE #2: Calling login always results in failure
I'm attempting to execute this line of code:

`var customer = await _revenueCatBilling.Login(_authService.CurrentUser.UniqueId);`

This always returns null and returns the following error on Android:

```
[0:] Maui.RevenueCat.InAppBilling.Services.RevenueCatBilling: Error: Login failed.

System.NullReferenceException: Object reference not set to an instance of an object.
   at Maui.RevenueCat.InAppBilling.Services.RevenueCatBilling.<Login>d__19.MoveNext() in D:\OneDrive\Programming\Csharp\Maui.RevenueCat.InAppBilling\Maui.RevenueCat.InAppBilling\Platforms\Android\RevenueCatBillingAndroid.cs:line 235
[DOTNET] [41m[30mfail[39m[22m[49m: Maui.RevenueCat.InAppBilling.Services.RevenueCatBilling[0]
[DOTNET]       Login failed.
[DOTNET]       System.NullReferenceException: Object reference not set to an instance of an object.
[DOTNET]          at Maui.RevenueCat.InAppBilling.Services.RevenueCatBilling.<Login>d__19.MoveNext() in D:\OneDrive\Programming\Csharp\Maui.RevenueCat.InAppBilling\Maui.RevenueCat.InAppBilling\Platforms\Android\RevenueCatBillingAndroid.cs:line 235

```

I've verified that _revenueCatBilling.IsInitialized() is true, am I missing something obvious that is needed to login successfully?

### PR DESCRIPTION
**Pull request by CameronVetter**
This fixes #2 by adding handling for null values coming back from the native Java code.

### CODE REVIEW

**Comment by Kebechet** [comment]
Thanks for the PR. 

Regarding changes. 
What do you think about following thing.
Instead of making those fields nullable, edit extension method [ToDateTime ](https://github.com/Kebechet/Maui.RevenueCat.InAppBilling/blob/main/Maui.RevenueCat.InAppBilling/Platforms/Android/Extensions/JavaDateExtensions.cs)so that it can accept nullable Date (right now it accepts just normal one and that is probably the main problem).

And even ManagementURL is nullable ?

**Comment by CameronVetter** [comment]
> Thanks for the PR.
> 
> Regarding changes. What do you think about following thing. Instead of making those fields nullable, edit extension method [ToDateTime ](https://github.com/Kebechet/Maui.RevenueCat.InAppBilling/blob/main/Maui.RevenueCat.InAppBilling/Platforms/Android/Extensions/JavaDateExtensions.cs)so that it can accept nullable Date (right now it accepts just normal one and that is probably the main problem).
> 
> And even ManagementURL is nullable ?

I see what you mean, that is in the spirit of the extension method.  I do think it would be better if the extension returned a nullable with a default value instead of a minvalue, that is a bit of a "magic number"   I'll update the PR.

**Comment by CameronVetter** [comment]
> Thanks for the PR.
> 
> Regarding changes. What do you think about following thing. Instead of making those fields nullable, edit extension method [ToDateTime ](https://github.com/Kebechet/Maui.RevenueCat.InAppBilling/blob/main/Maui.RevenueCat.InAppBilling/Platforms/Android/Extensions/JavaDateExtensions.cs)so that it can accept nullable Date (right now it accepts just normal one and that is probably the main problem).
> 
> And even ManagementURL is nullable ?

Yes customerInfo.ManagementUrl is null in my case.  ToString throws an exception if this is null, and since this is the default ToString this either needs to be handled the way I did it, or a new extension method needs to be created to handle it.  Let me know what you think and I'll update the PR.

**Comment by Kebechet** [comment]
Ok, this is much better. I went through iOS implementation and it wasnt 1:1.
As you can see here: https://github.com/Kebechet/Maui.RevenueCat.InAppBilling/blob/main/Maui.RevenueCat.InAppBilling/Platforms/iOS/RevenueCatBillingiOS.cs#L221-#L229

So to keep it unified please:
- Android
  - for ManagementURL please use null propagation like on [iOS](https://github.com/Kebechet/Maui.RevenueCat.InAppBilling/blob/main/Maui.RevenueCat.InAppBilling/Platforms/iOS/RevenueCatBillingiOS.cs#L228C25-L228C25)
  - in `JavaDateExtensions` please return `null` instead of default. It is a minor thing, but I prefer it this way to have it explicitly set
- iOS
  - edit  [NsDateExtensions](https://github.com/Kebechet/Maui.RevenueCat.InAppBilling/blob/main/Maui.RevenueCat.InAppBilling/Platforms/iOS/Extensions/NsDateExtensions.cs) so that it also returns `null`

after these changes I will merge it and release a new version.

**Comment by CameronVetter** [comment]
> Ok, this is much better. I went through iOS implementation and it wasnt 1:1. As you can see here: https://github.com/Kebechet/Maui.RevenueCat.InAppBilling/blob/main/Maui.RevenueCat.InAppBilling/Platforms/iOS/RevenueCatBillingiOS.cs#L221-#L229
> 
> So to keep it unified please:
> 
> * Android
>   
>   * for ManagementURL please use null propagation like on [iOS](https://github.com/Kebechet/Maui.RevenueCat.InAppBilling/blob/main/Maui.RevenueCat.InAppBilling/Platforms/iOS/RevenueCatBillingiOS.cs#L228)
>   * in `JavaDateExtensions` please return `null` instead of default. It is a minor thing, but I prefer it this way to have it explicitly set
> * iOS
>   
>   * edit  [NsDateExtensions](https://github.com/Kebechet/Maui.RevenueCat.InAppBilling/blob/main/Maui.RevenueCat.InAppBilling/Platforms/iOS/Extensions/NsDateExtensions.cs) so that it also returns `null`
> 
> after these changes I will merge it and release a new version.

Agreed, once I get it tested ill update the PR.

**Pull request merged**
